apiVersion: v1
kind: Service
metadata:
  name: wisecow-nodeport
  namespace: wisecow
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
  - port: 4499
    targetPort: 4499
    nodePort: 30499

